# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-18 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.IntegerField()),
                ('value2', models.IntegerField()),
                ('value3', models.IntegerField()),
                ('value4', models.IntegerField()),
                ('value5', models.IntegerField()),
                ('value6', models.IntegerField()),
                ('value7', models.IntegerField()),
                ('value8', models.IntegerField()),
                ('value9', models.IntegerField()),
                ('value10', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='book2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.IntegerField()),
                ('value2', models.IntegerField()),
                ('value3', models.IntegerField()),
                ('value4', models.IntegerField()),
                ('value5', models.IntegerField()),
                ('value6', models.IntegerField()),
                ('value7', models.IntegerField()),
                ('value8', models.IntegerField()),
                ('value9', models.IntegerField()),
                ('value10', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='book3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.IntegerField()),
                ('value2', models.IntegerField()),
                ('value3', models.IntegerField()),
                ('value4', models.IntegerField()),
                ('value5', models.IntegerField()),
                ('value6', models.IntegerField()),
                ('value7', models.IntegerField()),
                ('value8', models.IntegerField()),
                ('value9', models.IntegerField()),
                ('value10', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='book4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.IntegerField()),
                ('value2', models.IntegerField()),
                ('value3', models.IntegerField()),
                ('value4', models.IntegerField()),
                ('value5', models.IntegerField()),
                ('value6', models.IntegerField()),
                ('value7', models.IntegerField()),
                ('value8', models.IntegerField()),
                ('value9', models.IntegerField()),
                ('value10', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='book5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.IntegerField()),
                ('value2', models.IntegerField()),
                ('value3', models.IntegerField()),
                ('value4', models.IntegerField()),
                ('value5', models.IntegerField()),
                ('value6', models.IntegerField()),
                ('value7', models.IntegerField()),
                ('value8', models.IntegerField()),
                ('value9', models.IntegerField()),
                ('value10', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='book6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.IntegerField()),
                ('value2', models.IntegerField()),
                ('value3', models.IntegerField()),
                ('value4', models.IntegerField()),
                ('value5', models.IntegerField()),
                ('value6', models.IntegerField()),
                ('value7', models.IntegerField()),
                ('value8', models.IntegerField()),
                ('value9', models.IntegerField()),
                ('value10', models.IntegerField()),
            ],
        ),
    ]
