# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-19 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0002_auto_20170119_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book2',
            name='value1',
            field=models.DecimalField(decimal_places=7, max_digits=7),
        ),
        migrations.AlterField(
            model_name='book2',
            name='value10',
            field=models.DecimalField(decimal_places=7, max_digits=7),
        ),
        migrations.AlterField(
            model_name='book2',
            name='value2',
            field=models.DecimalField(decimal_places=7, max_digits=7),
        ),
        migrations.AlterField(
            model_name='book2',
            name='value3',
            field=models.DecimalField(decimal_places=7, max_digits=7),
        ),
        migrations.AlterField(
            model_name='book2',
            name='value4',
            field=models.DecimalField(decimal_places=7, max_digits=7),
        ),
        migrations.AlterField(
            model_name='book2',
            name='value5',
            field=models.DecimalField(decimal_places=7, max_digits=7),
        ),
        migrations.AlterField(
            model_name='book2',
            name='value6',
            field=models.DecimalField(decimal_places=7, max_digits=7),
        ),
        migrations.AlterField(
            model_name='book2',
            name='value7',
            field=models.DecimalField(decimal_places=7, max_digits=7),
        ),
        migrations.AlterField(
            model_name='book2',
            name='value8',
            field=models.DecimalField(decimal_places=7, max_digits=7),
        ),
        migrations.AlterField(
            model_name='book2',
            name='value9',
            field=models.DecimalField(decimal_places=7, max_digits=7),
        ),
        migrations.AlterField(
            model_name='book3',
            name='value1',
            field=models.DecimalField(decimal_places=7, max_digits=7),
        ),
        migrations.AlterField(
            model_name='book3',
            name='value10',
            field=models.DecimalField(decimal_places=7, max_digits=7),
        ),
        migrations.AlterField(
            model_name='book3',
            name='value2',
            field=models.DecimalField(decimal_places=7, max_digits=7),
        ),
        migrations.AlterField(
            model_name='book3',
            name='value3',
            field=models.DecimalField(decimal_places=7, max_digits=7),
        ),
        migrations.AlterField(
            model_name='book3',
            name='value4',
            field=models.DecimalField(decimal_places=7, max_digits=7),
        ),
        migrations.AlterField(
            model_name='book3',
            name='value5',
            field=models.DecimalField(decimal_places=7, max_digits=7),
        ),
        migrations.AlterField(
            model_name='book3',
            name='value6',
            field=models.DecimalField(decimal_places=7, max_digits=7),
        ),
        migrations.AlterField(
            model_name='book3',
            name='value7',
            field=models.DecimalField(decimal_places=7, max_digits=7),
        ),
        migrations.AlterField(
            model_name='book3',
            name='value8',
            field=models.DecimalField(decimal_places=7, max_digits=7),
        ),
        migrations.AlterField(
            model_name='book3',
            name='value9',
            field=models.DecimalField(decimal_places=7, max_digits=7),
        ),
        migrations.AlterField(
            model_name='book4',
            name='value1',
            field=models.DecimalField(decimal_places=7, max_digits=7),
        ),
        migrations.AlterField(
            model_name='book4',
            name='value10',
            field=models.DecimalField(decimal_places=7, max_digits=7),
        ),
        migrations.AlterField(
            model_name='book4',
            name='value2',
            field=models.DecimalField(decimal_places=7, max_digits=7),
        ),
        migrations.AlterField(
            model_name='book4',
            name='value3',
            field=models.DecimalField(decimal_places=7, max_digits=7),
        ),
        migrations.AlterField(
            model_name='book4',
            name='value4',
            field=models.DecimalField(decimal_places=7, max_digits=7),
        ),
        migrations.AlterField(
            model_name='book4',
            name='value5',
            field=models.DecimalField(decimal_places=7, max_digits=7),
        ),
        migrations.AlterField(
            model_name='book4',
            name='value6',
            field=models.DecimalField(decimal_places=7, max_digits=7),
        ),
        migrations.AlterField(
            model_name='book4',
            name='value7',
            field=models.DecimalField(decimal_places=7, max_digits=7),
        ),
        migrations.AlterField(
            model_name='book4',
            name='value8',
            field=models.DecimalField(decimal_places=7, max_digits=7),
        ),
        migrations.AlterField(
            model_name='book4',
            name='value9',
            field=models.DecimalField(decimal_places=7, max_digits=7),
        ),
    ]
